server:
  port: 8999

eureka:
  instance:
    hostname: apigateway
  client:
    serviceUrl: 
      defaultZone:http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-register : true
 


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
